// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneToManyMVC.Models;

namespace OneToManyMVC.Migrations
{
    [DbContext(typeof(OneToManyMVCContext))]
    partial class OneToManyMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OneToManyMVC.Models.Ambion", b =>
                {
                    b.Property<int>("AmbionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmbionName");

                    b.HasKey("AmbionId");

                    b.ToTable("Ambion");
                });

            modelBuilder.Entity("OneToManyMVC.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("OneToManyMVC.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentAmbionID");

                    b.Property<int>("CurrentGradeID");

                    b.Property<string>("StudentName");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAmbionID");

                    b.HasIndex("CurrentGradeID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("OneToManyMVC.Models.Student", b =>
                {
                    b.HasOne("OneToManyMVC.Models.Ambion", "Ambion")
                        .WithMany("Students")
                        .HasForeignKey("CurrentAmbionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneToManyMVC.Models.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("CurrentGradeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
